### ISSUE TITLE
Creating Javadoc comments causes "Invalid ranges during formatting..." errors.

### ISSUE THREAD

**Issue by EBatTiVo** [HaxeFoundation/intellij-haxe#350] opened 2015-09-15 06:09 UTC
Before a function that does not have a comment, type the beginning of a javadoc comment "/**" and press enter.

Expected: A new javadoc style comment is created and filled out appropriately.

Found: An error is posted, and incomplete comments are added incorrectly.  

For instance, when I tried it for the function "test2", typing at the beginning of the line above the function definition, the following resulted:

``` haxe
    public function test()
        for (i in  0...10)
            {trace(i);};/**
    *
**/
    public function test2(size:Int)
        return var a : Array<Int> = [for (i in 0...size) i];
```

**Comment by EBatTiVo** [comment] 2015-09-15 06:10
Here is the stack dump for the error:

```
Invalid ranges during formatting in Language: Haxe
java.lang.Throwable
	at com.intellij.plugins.haxe.ide.formatter.HaxeFormattingModelBuilder.createModel(HaxeFormattingModelBuilder.java:1)
	at com.intellij.formatting.InitialInfoBuilder.assertInvalidRanges(InitialInfoBuilder.java:402)
	at com.intellij.formatting.WhiteSpace.append(WhiteSpace.java:127)
	at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:165)
	at com.intellij.formatting.InitialInfoBuilder.prepareToBuildBlocksSequentially(InitialInfoBuilder.java:95)
	at com.intellij.formatting.FormatProcessor$WrapBlocksState.<init>(FormatProcessor.java:1320)
	at com.intellij.formatting.FormatProcessor.<init>(FormatProcessor.java:178)
	at com.intellij.formatting.FormatProcessor.<init>(FormatProcessor.java:163)
	at com.intellij.formatting.FormatterImpl$2.buildProcessor(FormatterImpl.java:251)
	at com.intellij.formatting.FormatterImpl$MyFormattingTask.prepare(FormatterImpl.java:907)
	at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:306)
	at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:258)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.a(CodeFormatterFacade.java:131)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:95)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processElement(CodeFormatterFacade.java:91)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:103)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:90)
	at com.intellij.codeInsight.editorActions.EnterHandler$DoEnterAction.a(EnterHandler.java:559)
	at com.intellij.codeInsight.editorActions.EnterHandler$DoEnterAction.a(EnterHandler.java:514)
	at com.intellij.codeInsight.editorActions.EnterHandler$DoEnterAction.run(EnterHandler.java:364)
	at com.intellij.codeInsight.editorActions.EnterHandler.a(EnterHandler.java:171)
	at com.intellij.codeInsight.editorActions.EnterHandler.access$000(EnterHandler.java:54)
	at com.intellij.codeInsight.editorActions.EnterHandler$1.run(EnterHandler.java:76)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:112)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:121)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:109)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:73)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:222)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)



java.lang.NullPointerException
	at com.intellij.formatting.FormatProcessor$ApplyChangesState.doIteration(FormatProcessor.java:1451)
	at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1268)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:266)
	at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:917)
	at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:308)
	at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:258)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.a(CodeFormatterFacade.java:131)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:95)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processElement(CodeFormatterFacade.java:91)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:103)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:90)
	at com.intellij.codeInsight.editorActions.EnterHandler$DoEnterAction.a(EnterHandler.java:559)
	at com.intellij.codeInsight.editorActions.EnterHandler$DoEnterAction.a(EnterHandler.java:514)
	at com.intellij.codeInsight.editorActions.EnterHandler$DoEnterAction.run(EnterHandler.java:364)
	at com.intellij.codeInsight.editorActions.EnterHandler.a(EnterHandler.java:171)
	at com.intellij.codeInsight.editorActions.EnterHandler.access$000(EnterHandler.java:54)
	at com.intellij.codeInsight.editorActions.EnterHandler$1.run(EnterHandler.java:76)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:112)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:121)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:109)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:73)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:222)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:56)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:206)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:38)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:203)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:342)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:422)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:333)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:324)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:200)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:98)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:109)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:83)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:576)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:625)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:475)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:538)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:269)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:184)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:174)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:169)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

```

**Comment by EBatTiVo** [comment] 2015-09-15 06:12
@Soywiz - Carlos, do you want to take a look at this?

**Comment by EBatTiVo** [comment] 2015-09-17 23:26
See also #334.

**Comment by as3boyan** [comment] 2016-02-05 19:26
Not catch-able bug in 14.1.6
Fixed in IDEA 15

**Comment by EBatTiVo** [comment] 2016-02-05 21:33
I'm not sure that I understand you comment.  Do you mean that the bug is not fixable in 14, or what?  It's plugin code that's throwing the error (based upon the stack trace above), so we should have control over that..

**Comment by EBatTiVo** [comment] 2016-03-02 18:04
We (TiVo) needs this fixed for v14 releases.

**Comment by as3boyan** [comment] 2016-03-07 12:22
I mean that IMHO it is out of my work on plugin

>It's plugin code that's throwing the error (based upon the stack trace above)

```
at com.intellij.plugins.haxe.ide.formatter.HaxeFormattingModelBuilder.createModel(HaxeFormattingModelBuilder.java:1)
```

Line 1 contains not much actually ""
Do you see that it is not my thing to fix JetBrains stuff, this should be reported to their tracker, because I think there is a bug (unhandled) in IntelliJ IDEA 14

**Comment by EBatTiVo** [comment] 2016-03-07 21:24
@as3boyan Don't worry about this bug, then.  

As far as the line it's reporting is concerned, for this type of bug, the reporter is cheating a bit and reporting the formatter that created the unbalanced range markers and shows line 1 because it doesn't know which line number the markers were created at.  The HaxeFormattingModelBuilder wasn't really on the stack, it was the model that created the unbalanced tags and was being validated.  Therefore, my belief is that the bug is twofold: the unbalanced tags are created by the haxe plugin; and there is indeed a bug in IntelliJ where it doesn't gracefully abort the process when this error occurs.  If we fix the first, the second will never occur.

**Comment by mayakwd** [comment] 2017-09-25 17:39
Is this bug still exists? I can't reproduce it.

**Comment by EricBishton** [comment] 2017-09-25 18:32
It still exists in IDEA 14.  However, the 0.11.0 was announced as the last release supporting v14, so this may just be closed when I actually stop delivering v14 releases.

The 0.11.1 release had about 60 users each for v14 and v15.  
0.11.0 had 60 and 75 users for 14 and 15, respectively.
0.10.1 had several hundred for each.

**Comment by EricBishton** [comment] 2017-09-25 18:52
Just to be clear, though.  I haven't checked v14 for this issue recently.

**Comment by mayakwd** [comment] 2018-05-14 08:38
Not relevant anymore

**Closed by mayakwd** 2018-05-14 08:38 UTC
Labels: Priority 1, bug
