### ISSUE TITLE
Could not find haxelib lime

### ISSUE THREAD

**Issue by xraven13** [HaxeFoundation/intellij-haxe#338] opened 2015-07-19 18:08 UTC
While testing it on Windows, I get t error "Could not find haxelib "lime", does it needs to be installed?"

This is strange because I am using the same Haxetoolkit as I used with FlashDevelop and Sublime Text 2, so why this wouldn't work ?

**Comment by EBatTiVo** [comment] 2015-07-20 05:24
I'll bet dollars to donuts you don't have the paths to neko and haxelib set up in the Platform SDK (File->Project Structure->SDKs->{your haxe sdk}->Haxelib executable).  Please try setting the values to valid executable names.

**Comment by xraven13** [comment] 2015-07-20 08:38
How much ? :)

![111](https://cloud.githubusercontent.com/assets/959518/8772287/4edf8e9e-2ecb-11e5-8129-1c6a890012b9.png)
![1112](https://cloud.githubusercontent.com/assets/959518/8772292/580a4f7c-2ecb-11e5-96e6-6817cf3bcb15.png)
![11113](https://cloud.githubusercontent.com/assets/959518/8772295/5c89e152-2ecb-11e5-98e6-c4129b0878ce.png)
![111114](https://cloud.githubusercontent.com/assets/959518/8772302/641106a8-2ecb-11e5-926a-f5f7496c2dc8.png)
![11115](https://cloud.githubusercontent.com/assets/959518/8772306/683e0ce4-2ecb-11e5-8e93-0e60b077a3b1.png)

**Comment by EBatTiVo** [comment] 2015-07-20 21:48
Can you please give us a dump of the "Message" pane where you see the error message when you try compiling?  The first line(s) tell us the exact command that was run.  

Also, if you use environment variables to set up your haxe development environment, make sure they are in effect when you start IDEA.  (The easy way: start IDEA from the same shell/command line session from which you run the compiler successfully.)

**Comment by xraven13** [comment] 2015-07-21 16:35
Is this what you mean by dump of the Message pane ? ( below screenshot )
![32323](https://cloud.githubusercontent.com/assets/959518/8806447/06ce932c-2fd7-11e5-8a3d-aa7154b951e2.png)

**Comment by EBatTiVo** [comment] 2015-07-21 19:19
> Is this what you mean by dump of the Message pane ?
Yes, exactly.

OK, you're getting the proper command line.  The error message may be correct.  This is probably an environmental issue.  If you let FlashDevelop install all of your haxe tools for you, your installation may need some tweaking.  Setting up a Haxe development environment is one thing that FlashDevelop does well and IDEA doesn't attempt to do at all.

So, start with running your build from the command shell.  If you cannot run the given command (everything after the "Executing:" label in the message above) from there, then IDEA won't be able to use it either.  If you can run it from the command shell, try starting IDEA from the command shell and try your compilation from that instance.  If everything works, then you know it's an environment issue.  (And, if what I'm writing here is all greek to you, then you need to go to the haxe foundation's web site, install the tools from scratch and get the examples working from your Windows Command Shell.)

When this works with your other environments, do you build for the OpenFL target?

Do you have lime installed?  Open the command window inside of IDEA  (Tools->Open Terminal).  At the command prompt, type "haxelib path lime".  You will either see some information about the library, or a message that the library is not installed.  Use "haxelib install lime" to get it if it's not already there.

**Comment by xraven13** [comment] 2015-07-21 20:06
Thanks !

Flash Develop didn't install anything, what I do is this :
- I have HaxeToolkit folder that was setup through cmd with some tweaks to it depending on the project
- when I want that project compiles with specific HaxeToolkit folder, I use command haxelib setup in cmd, and I set the correct path to that folder 

So this is the environmental variable you was talking about, I assumed it is something else, the one that Windows uses. How this can be fixed, is there any way to set the enviromental variable inside of IDEA ?  

My game uses OpenFL.

Yes, I have lime installed. Typing "haxelib path lime" showed this.
-L lime/0,9,0/ndll/
C:\HaxeToolkit2\haxe\lib/lime/0,9,0/
-D lime=0.9.0

**Comment by EBatTiVo** [comment] 2015-07-21 23:47
That sounds like you have a working environment, outside of FlashDevelop.  Good.

Does your build work when you start the command shell inside of IDEA (Tools->Open Terminal) and run the same build command?  If it doesn't work from there, then IDEA isn't getting the same environment as your "cmd" command shell.  (And, by environment, I mean both the Environment Variables -- like %PATH%, %HAXEPATH%, etc. -- as well as the haxe toolkit configuration.)

> is there any way to set the enviromental variable inside of IDEA

Not directly.  They are inherited from the process that starts IDEA.  Inside of IDEA, you can usually add variables to command lines via -D switches, but I don't know whether haxelib accepts them.

To let IDEA have the same environment as your command shell, you must start it from the command shell you've configured -- NOT the menu item or desktop icon.  So, to run idea from the command shell, execute the command: <idea_install_directory>/bin/idea.bat.  Here is a concrete example:
```
C:\Program Files (x86)\JetBrains\IntelliJ IDEA 13.1.6\bin\idea.bat 
```

Then you can try the experiment above again (run the Tools->Open Terminal command and start your build on that cmd shell).

**Comment by xraven13** [comment] 2015-07-22 09:10
I opened IDEA from cmd, but it still didn't work. 
Checking the path to lime works.

Usually I build with Flash Develop, I tried doing it from terminal ( at least I think that's the right command ), but whitespace of folder name is problem, after I changed it, the IDEA lost reference to whole project. Quotation marks don't work. I tried looking around, but can't find solution.. Is there any way to get the folder back without losing all settings  ?

**Comment by EBatTiVo** [comment] 2015-07-22 16:28
You can try just changing the directory name back to what it was.  

IDEA projects are stored in *.ipr files, modules in *.iml files, and workspaces in *.iws files.  They are simple XML files and you can edit them in any text editor.  You can fix up the paths there.

**Comment by xraven13** [comment] 2015-07-23 10:23
I tried making project from start.

What I noticed is that when I setup SDK, the Intellij IDEA automatically sets neko path to usually default path "HaxeToolkit" instead of "HaxeToolkit2" that I selected. So while Haxe path was okay, Neko path wasn't. 

Now I get different error, shown below in screenshot. 

And also "haxelib path lime" doesn't work anymore, it is not recognizable. And I also tried to open the IDEA with cmd... Uh I am afraid if I cannot set this up on Windows, how it's gonna work on Macbook than... :))

Does it maybe matters that I have two folders marked as source ? src and source ? When I double click on src I can set the settings, but double click on source folder with source code, only opens it. Maybe I should delete original src folder and set the settings for folder name "source" ? This is kinda confusing. :)

**Comment by EBatTiVo** [comment] 2015-07-23 18:13
If this is all confusing, perhaps you shouldn't be using a custom environment? ;)  MacOS is a lot more like Linux than Windows. (It's really a derivative of BSD Unix.)  Environments (environment variables and how they are passed to child tasks) are the same in all OSes.  The Haxe plugin behavior is the same for all OSes as well.

From the error display in your last message, it looks like you are using an old version of the plugin.  The current version is 0.9.5.  You can find the version by looking at the plugin page (File->Settings->Plugins{Left Pane}->Haxe Plugin{Right Pane}).  0.9.5 does a better job of displaying errors.  If you can't compile in the CMD shell, then you have very little chance of getting it to work with IDEA.  You need to go back to the beginning and make sure that everything works in the CMD shell.

Using both Source and src directories in a single project is not a problem.  IDEA adds the "Sources" property to the src directory by default.  If you also want to use another directory, you need to tell idea about it in the modules screen of the project structure dialog (File->Project Structure->Modules{left pane}->[your module]{middle pane}->Sources Tab{right pane})  Right click on the directory (in your case, the Sources directory) to open thecontext menu and select the "Sources" menu item to mark it for use -- make sure that it is not also marked as "Excluded."

If you need general IDEA-oriented help, there is an active Haxe community available on IRC.  You'll get more informed and immediate answers using the community forums.
http://old.haxe.org/com/meeting/irc
http://blog.jetbrains.com/idea/2012/05/get-involved-into-intellij-idea-community/

**Comment by xraven13** [comment] 2015-07-23 19:19
I don't mind custom environment, and I need IDEA since it is only solution for my Macbook. :)

I am already using Haxe Plugin 0.9.5. 

I followed and compared 3 tutorials so far, and I did everything they did. There was this little mistake with IDEA automatically selecting wrong folder for neko even though I never selected that folder, but the other one. But now I did that, it works even less which is weird.

![image](https://cloud.githubusercontent.com/assets/959518/8859802/f0fd9b42-317f-11e5-9cc0-cb39c6882d32.png)

**Comment by EBatTiVo** [comment] 2015-07-23 19:58
Just a thought: If you've changed the haxelib environment, (via "haxelib setup" from "c:\Haxelib\lib" to "c:Haxelib2\lib"), you probably have to re-install all of the haxe libraries (e.g. lime, flixel) because haxelib is using a different path and cannot find the old ones; you will have a second copy of them.  The stock version of haxelib cannot use multiple library paths.

**Comment by xraven13** [comment] 2015-07-24 08:14
All haxe libraries work perfectly fine in Flash Develop and Sublime Text. 

User can set the current library via cmd by using haxelib setup path command.

So IDEA have trouble with this ?

**Comment by EBatTiVo** [comment] 2015-07-24 16:43
Here are some general things to do:
* Check your project.xml to make sure that it isn't conflicting with the IDEA settings.
* Read all of the .iml and .ipr files for your project to see if there is anything that appears out of whack.
* Dump your environment and look for anything that stands out as odd.  Particularly look for anything with the word Haxe.
* Make sure that you can run the build command from the command line.  
* Make sure that haxelib is in your %PATH%.

IDEA is agnostic of haxelib setup path, though it does try to use the environment variable "HAXEPATH" to set the default haxe installation directory. (On non-windows systems it also tries /usr/lib/haxe if HAXEPATH isn't defined.)  If "HAXEPATH" isn't set (or doesn't exist in /usr/lib/haxe), then IDEA will not be able to use the default SDK without you specifying *everything* in the setup dialogs.

It also looks for the environment variable "HAXE_STD_PATH".  If that's not set, it will search the subtree of "HAXEPATH" for the "std" directory.  If neither is set, then it won't be able to find your haxe installation.  It does a similar thing with "HAXE_DOC_PATH" for documentation.

There is some code that tries to figure out that you don't have a library installed and you are trying to refrerence it.  It was designed to suggest libraries to install and prompt you whether to install them automatically.  I've never tested that functionality.

At this point, if I were you, I would start with a new "Hello World!" type project and get that to work in IDEA.  Then you'll have a known working base to start from.  The issues are going to be found in the way you have things set up.  Do this without depending upon FlashDevelop or Sublime2 -- not that I'm discouraging their use; but because FlashDevelop helps with configuration, I suspect that it's setting something up that is not translating to IDEA well.  If you have a clean machine (or a clean VM), a brand new setup would be ideal.

If you're so inclined, check the sources for the Haxe plugin so that you can understand what's going on: src/common/com/intellij/plugins/haxe/config/HaxeSdkUtil.java, HaxeSdkType.java, src/common/com/intellij/plugins/haxe/haxelib/HaxelibSdkUtils.java.

**Comment by EricBishton** [comment] 2017-05-21 03:32
This question is two years old.  I'm closing it.

**Closed by EricBishton** 2017-05-21 03:32 UTC
Labels: Awaiting Clarification, question
