### ISSUE TITLE
Use-case suggestion

### ISSUE THREAD

**Issue by react-dev-uz** [HaxeFoundation/intellij-haxe#1096] opened 2023-02-07 14:42 UTC
### 
![Screenshot 2023-02-07 194152](https://user-images.githubusercontent.com/119865673/217276153-5fa1e742-a45e-4e98-b1b6-43658419177a.png)
Hello, please update the plugin for `Intellij` idea. Because it does `not support` versions after `2020`.

**Comment by Aurel300** [comment] 2023-02-07 14:50
Duplicate of #1083.

**Closed as not planned by Aurel300** 2023-02-07 14:50 UTC
