### ISSUE TITLE
Invalid assignment expressions from scoping issues

### ISSUE THREAD

**Issue by jasonsturges** [HaxeFoundation/intellij-haxe#176] opened 2015-03-19 21:57 UTC
Not sure if this involves scoping issues between declarations and packages; however, there are some assignment expression errors reported by the IDE from my [OpenFL Haxe Performance Test](https://github.com/jasonsturges/openfl-haxe-performance-test) project.

In base class [`TestSuite`](https://github.com/jasonsturges/openfl-haxe-performance-test/blob/master/Source/performance/model/TestSuite.hx#L14) I defined a variable named `tests`:

```
package performance.model;
class TestSuite extends EventDispatcher {
    public var tests:Array<AbstractTest>;
```

When extended in subclasses like [`BitwiseTestSuite`](https://github.com/jasonsturges/openfl-haxe-performance-test/blob/master/Source/tests/BitwiseTestSuite.hx#L26) the IDE reports an error around variable `tests`.

```
package tests;
class BitwiseTestSuite extends TestSuite {
    public function new() {
        tests = [];
```

At the assignment the IDE reports error:

> '(', <assign expression>, '=>', ID, OPEN_QUOTE, cast, if, new, super, switch, this, try or '{' expected, got '['
> '[' unexpected

![image](https://cloud.githubusercontent.com/assets/1213591/6741465/98575fb0-ce55-11e4-8dd1-25844bf212ac.png)

Jump to declaration is resolving to the package name, which is also `tests`; however, I believe that's a separate issue.  Isolating that test, I do not receive the assignment error; however, jump to declaration still takes me to the package instead of the variable as seen here:

```
package tests;
class TestClass {
    public function new() {
        var tests:Array<Int>;
        tests = [1, 2, 3];
    }
}
```

TIR: STB-9365

**Comment by EBatTiVo** [comment] 2015-03-19 23:14
While the bug is written as though variables from the base class are not being resolved, that is not the case here (though it may still be true).  What you're seeing is a parsing error, which comes long before the referenced variable is looked up.  In fact, I'll bet dollars-to-donuts that the parsed AST contains a PARSE_ERROR, rather than a REFERENCE_EXPRESSION token for 'test' at that point. 

In the examples you posted, the error may be caused by a faulty 'newRecovery' rule (which I've been tweaking recently).  However, that's probably not the case for the code in the image that you posted, so we'll have to test that separately.

Expecting 'if', 'switch', or 'try' shouldn't be part of that message.  I presume that it's because the parser is looking for an 'expression', which allows those things.  We should probably specialize an 'assignableExpression' element to deal with that.   However, that's a rabbit trail...

The jump-to-declaration preferring a package to a local variable is a known issue #95 which was closed.  Apparently, this is a regression; I've re-opened that bug.  

(BTW, I presume @jasonsturges, that you are testing using Idea 14.0 on OSX?)

**Comment by jasonsturges** [comment] 2015-03-20 02:29
@EBatTiVo Sorry for not providing details, environment is:

- Haxe Support plugin v0.9.2 (From JetBrains repository)
- Mac OS X 10.9.5
- IntelliJ IDEA 14.0.3 build #IU-139.1117 built January 21, 2015
- JRE 1.6.0_65-b14-462-11M4609 x86_64
- haxe 3.1.3
- lime 2.0.0 2.0.1 [2.0.2]
- openfl 2.0.1 [2.1.8]

**Comment by eliasku** [comment] 2016-02-19 11:19
Must be fixed.

@jasonsturges Please verify on 0.9.9

**Comment by EBatTiVo** [comment] 2016-03-02 17:08
@eliasku @jasonsturges It would be nice if the recent resolution changes have fixed this bug.  However, I don't want to close this one without retesting it explicitly because it's caused by a parsing error and we haven't checked in any changes to that area recently.

**Comment by jasonsturges** [comment] 2016-03-02 19:49
@eliasku @EBatTiVo With heavy workload, I'm deep in other technologies at the moment.

Without significant effort, you can also verify by pulling my [OpenFL Haxe Performance Test](https://github.com/jasonsturges/openfl-haxe-performance-test) repo, and looking at the `tests = []` assignment from any extended test suite class.

Otherwise, I'll try to get to it soon.

**Comment by mayakwd** [comment] 2017-09-26 13:23
Not reproducible

**Comment by EricBishton** [comment] 2017-09-26 18:40
@mayakwd How did you test for reproducibility?

**Comment by EricBishton** [comment] 2017-11-25 06:27
Tested on 0.11.2 (by downloading the test suite mentioned above).  All issues appear fixed.

**Closed by EricBishton** 2017-11-25 06:27 UTC
Labels: bug, Priority 2
