### ISSUE TITLE
Intellij freezing for a moment after changing project target

### ISSUE THREAD

**Issue by barisyild** [HaxeFoundation/intellij-haxe#1127] opened 2023-07-14 18:51 UTC
After changing the project target, Intellij freezes for about 30 seconds to 1 minute and receives no input.

**Comment by m0rkeulv** [comment] 2023-07-14 18:54
i am unable to reproduce this issue, from what target to what target are you changing, and does intellij show any kind of progress bar anywhere ? (ohter useful info.what version of intellij/android studio  are you using and what version of the plugin)


I know intellij can lock up for a while  if its using files from a network drive thats not responding etc, i have this prolem when i disable hyper-v because intellij can not access WSL file system anymore, but that would not be  the plugins fault that's just intellij in general.

**Comment by m0rkeulv** [comment] 2023-07-14 19:16
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/46576573-b831-4ad6-b6d7-a4e958aef010)
if you could share some  troubleshooting information that could help

you could also run the Activity monitor when  changing project and see what it says
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/d5a49e36-9c5e-4861-92dc-76cc6b1daa49)

**Comment by m0rkeulv** [comment] 2023-07-17 10:24
fixed in 1.4.7

**Closed as completed by m0rkeulv** 2023-07-17 10:24 UTC
Labels: release-1.4.7
