### ISSUE TITLE
Project fails to launch after compile for IDEA 14

### ISSUE THREAD

**Issue by peteshand** [HaxeFoundation/intellij-haxe#82] opened 2014-12-18 23:27 UTC
I'm compiling a very basic OpenFL project, it compiles fine, but then nothing else happens.
I would expect the project to open in chrome using the build in webserver or within the flash player, is this what is meant to happen? or am I missing something fundamental here?

I'm testing OpenFL with both flash and html targets
and using IntelliJ IDEA 14 Ultimate

**Comment by EBatTiVo** [comment] 2015-04-21 01:56
Duplicate of #66?  This bug is for OpenFL, #66 is for Neko.

**Comment by sganapavarapu1** [comment] 2015-04-21 16:04
I'm able to launch and debug my application in IntelliJ IDEA 14.1.1 build 141.178 Ultimate edition
(openfl with lime toolchain for cpp target on linux centos 6.5)

**Comment by CanIGetaPR** [comment] 2024-04-22 12:43
Can't reproduce with openfl bunnymark sample and plugin version 1.5.3 and IDEA 2024.

**Closed by CanIGetaPR** 2024-04-22 12:43 UTC
Labels: bug, duplicate, Priority 4, Needs Verification
