### ISSUE TITLE
Flixel Index Error

### ISSUE THREAD

**Issue by barisyild** [HaxeFoundation/intellij-haxe#978] opened 2019-12-20 00:56 UTC
Error while indexing C:\HaxeToolkit\haxe\lib\flixel\4,6,3\flixel\system\debug\interaction\tools\Transform.hx
To reindex this file IDEA has to be restarted

java.lang.NullPointerException
	at com.intellij.plugins.haxe.model.HaxeImportModel.lambda$getExposedMember$5(HaxeImportModel.java:164)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.intellij.plugins.haxe.model.HaxeImportModel.getExposedMember(HaxeImportModel.java:165)
	at com.intellij.plugins.haxe.model.HaxeImportModel.exposeByName(HaxeImportModel.java:143)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.lambda$getQName$6(HaxeResolveUtil.java:721)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.tryAdvance(Streams.java:82)
	at java.base/java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.getQName(HaxeResolveUtil.java:722)
	at com.intellij.plugins.haxe.ide.index.HaxeInheritanceIndex$MyDataIndexer.getQNameAndCache(HaxeInheritanceIndex.java:135)
	at com.intellij.plugins.haxe.ide.index.HaxeInheritanceIndex$MyDataIndexer.map(HaxeInheritanceIndex.java:117)
	at com.intellij.plugins.haxe.ide.index.HaxeInheritanceIndex$MyDataIndexer.map(HaxeInheritanceIndex.java:88)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:312)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.mapInput(VfsAwareMapReduceIndex.java:109)
	at com.intellij.util.indexing.impl.MapReduceIndex.calculateUpdateData(MapReduceIndex.java:268)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:250)
	at com.intellij.util.indexing.FileBasedIndexImpl.updateSingleIndex(FileBasedIndexImpl.java:1680)
	at com.intellij.util.indexing.FileBasedIndexImpl.lambda$doIndexFileContent$28(FileBasedIndexImpl.java:1605)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:656)
	at com.intellij.util.indexing.FileBasedIndexImpl.doIndexFileContent(FileBasedIndexImpl.java:1564)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1550)
	at com.intellij.util.indexing.UnindexedFilesUpdater.lambda$indexFiles$0(UnindexedFilesUpdater.java:109)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$0(CacheUpdateRunner.java:219)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.lambda$run$1(CacheUpdateRunner.java:235)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:232)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by yigithanyucedag** [comment] 2019-12-20 03:01
+1

**Comment by EricBishton** [comment] 2019-12-20 06:35
Another duplicate of #971 . I did a fix in 12bc205 that fixes the problem. You can pick up a test build at https://github.com/EricBishton/intellij-haxe/releases/tag/Post1.2TestBuild.2.

**Closed by EricBishton** 2019-12-20 06:35 UTC
Labels: bug, duplicate

**Comment by barisyild** [comment] 2019-12-20 22:37
In file: file://C:/HaxeToolkit/haxe/lib/nape-haxe4/2,0,21/nape/phys/Body.hx

com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.plugins.haxe.lang.psi.HaxeClass$1 #  because: parent is null
invalidated at: no info
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:76)
	at com.intellij.extapi.psi.ASTDelegatePsiElement.getManager(ASTDelegatePsiElement.java:53)
	at com.intellij.psi.impl.PsiElementBase.getProject(PsiElementBase.java:214)
	at com.intellij.plugins.haxe.lang.psi.HaxeClassResolveResult.getResult(HaxeClassResolveResult.java:159)
	at com.intellij.plugins.haxe.lang.psi.HaxeClassResolveResult.create(HaxeClassResolveResult.java:109)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.tryResolveClassByInferringMethodReturnType(HaxeResolveUtil.java:699)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.getHaxeClassResolveResultInternal(HaxeResolveUtil.java:602)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.getHaxeClassResolveResult(HaxeResolveUtil.java:519)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.getHaxeClassResolveResultInternal(HaxeResolveUtil.java:584)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.getHaxeClassResolveResult(HaxeResolveUtil.java:519)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveHaxeClassInternal(HaxeReferenceImpl.java:562)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveHaxeClass(HaxeReferenceImpl.java:282)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.resolveChain(HaxeResolver.java:277)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.checkIsChain(HaxeResolver.java:190)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.doResolve(HaxeResolver.java:116)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:147)
	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:71)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:146)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:236)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.resolve(HaxeResolver.java:77)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.multiResolve(HaxeReferenceImpl.java:216)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveToComponentName(HaxeReferenceImpl.java:233)
	at com.intellij.plugins.haxe.ide.annotator.HaxeColorAnnotator.annotate(HaxeColorAnnotator.java:67)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:126)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:108)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:351)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:291)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:311)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:93)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:314)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:282)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:227)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:997)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:167)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:157)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by EricBishton** [comment] 2019-12-20 22:42
The last entry is a different issue.  Please file a new issue for that stack trace, with version details (IDEA and plugin), and how to reproduce.
