### ISSUE TITLE
Unhandled exception while resolving generic classes.

### ISSUE THREAD

**Issue by emanuel-macoun** [HaxeFoundation/intellij-haxe#911] opened 2019-02-05 14:36 UTC
I've got following error when opening my Haxe project.
My configuration is: 
Haxe plugin v1.1
IntelliJ IDEA 2018.3.4 (Ultimate Edition)
Build #IU-183.5429.30, built on January 29, 2019
JRE: 1.8.0_152-release-1343-b26 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.3

```
java.util.ConcurrentModificationException
	at gnu.trove.THashIterator.nextIndex(THashIterator.java:83)
	at gnu.trove.TIterator.hasNext(TIterator.java:57)
	at com.intellij.plugins.haxe.lang.psi.HaxeGenericSpecialization.clone(HaxeGenericSpecialization.java:53)
	at com.intellij.plugins.haxe.lang.psi.HaxeClassResolveResult.clone(HaxeClassResolveResult.java:65)
	at com.intellij.plugins.haxe.lang.psi.HaxeClassResolveResult.create(HaxeClassResolveResult.java:194)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.getHaxeClassResolveResult(HaxeResolveUtil.java:387)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.tryResolveClassByTypeTag(HaxeResolveUtil.java:480)
	at com.intellij.plugins.haxe.util.HaxeResolveUtil.getHaxeClassResolveResult(HaxeResolveUtil.java:422)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveHaxeClassInternal(HaxeReferenceImpl.java:512)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveHaxeClass(HaxeReferenceImpl.java:282)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.tryGetLeftResolveResult(HaxeReferenceImpl.java:778)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.getSpecialization(HaxeReferenceImpl.java:132)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveHaxeClassInternal(HaxeReferenceImpl.java:512)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveHaxeClass(HaxeReferenceImpl.java:282)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.tryGetLeftResolveResult(HaxeReferenceImpl.java:778)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.getSpecialization(HaxeReferenceImpl.java:132)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveHaxeClassInternal(HaxeReferenceImpl.java:512)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveHaxeClass(HaxeReferenceImpl.java:282)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.resolveChain(HaxeResolver.java:272)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.checkIsChain(HaxeResolver.java:185)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.doResolve(HaxeResolver.java:115)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:150)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:98)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:149)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:239)
	at com.intellij.plugins.haxe.lang.psi.HaxeResolver.resolve(HaxeResolver.java:76)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.multiResolve(HaxeReferenceImpl.java:216)
	at com.intellij.plugins.haxe.lang.psi.impl.HaxeReferenceImpl.resolveToComponentName(HaxeReferenceImpl.java:233)
	at com.intellij.plugins.haxe.ide.annotator.HaxeColorAnnotator.annotate(HaxeColorAnnotator.java:65)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:120)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.runVisitors(GeneralHighlightingPass.java:353)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$collectHighlights$5(GeneralHighlightingPass.java:286)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:313)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.lambda$analyzeByVisitors$6(GeneralHighlightingPass.java:316)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:71)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:316)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:283)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:227)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:69)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:423)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1168)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:416)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:415)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:391)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:147)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:222)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:389)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by EricBishton** [comment] 2020-09-08 04:02
This looks like it could occur if we had a generic that refers to itself, something like:
``` haxe
class someClass<T> extends otherClass<someClass<T>> {
}
```
which happens in some code bases.  I'm not sure if this is really the case, though.

The exception is being thrown by gnu.trove.THashMap's iterator, though trove shouldn't be used any longer.  If replaced with java.util.ConcurrentHashMap, the exception isn't thrown by that class, though the results may be incorrect because we are (I assume) adding to a Map while we are iterating over it (trying to do a shallow copy).  Or, perhaps the Map is being created in a cache while we are reading from the same cache.

@emanuel-macoun Is there any chance that you still have a copy of the project that was causing this issue.  None of my projects repro the problem.

**Comment by m0rkeulv** [comment] 2024-08-24 19:03
The code handling generics has changed a lot  and i am unable to  reproduce any issues with classes using it self as a type parameter, so i am closing this one for now.

test code: 
```haxe

package debug;
class OtherClass<T> {
    var y:T;
}

class SomeClass<T:SomeClass> extends OtherClass<SomeClass<T>> {
    public var x:T;
    function new () {
        var test = y.x;
    }
}
````
![image](https://github.com/user-attachments/assets/4e80e61d-d155-43a8-9ec5-5bbb8095e513)

**Closed by m0rkeulv** 2024-08-24 19:03 UTC
Labels: bug, Priority 2
