### ISSUE TITLE
Project view is empty for open project

### ISSUE THREAD

**Issue by uuf6429** [HaxeFoundation/intellij-haxe#665] opened 2017-09-12 22:24 UTC
I had created a new PHP project and then installed the plugin. After restarting the IDE, the left "Project" panel stays empty with a message that roughly says "Nothing here". I noticed there's a small spinner in the top-right corner that stays there.

Things I tried (and failed):
- restarting the IDE
- closing and reopening the project
- reinstalling the plugin

I noticed that if "Project" is switched to "Project Files", the files of the project do show up correctly.

----

Environment: PhpStorm 2017.2.3, Haxe Support 0.11.1

----

I don't have immediate use for this plugin (I'm not writing Haxe yet), it's just that I thought to try it out and found this bug.

**Comment by uuf6429** [comment] 2018-02-17 01:47
I've had renewed interest in Haxe and retried this plugin again _unsuccessfully_ on PhpStorm 2017.3.
Issue's been marked as a duplicate, but I couldn't find which issue it's a duplicate of. @EricBishton can you please post a link? You can free close this ticket afterwards.

**Comment by EricBishton** [comment] 2018-02-17 01:58
Well, I can't find the issue that this is a duplicate of, either.  Removing the label.

**Closed** 2024-08-18 17:16 UTC
Labels: bug, Priority 4
