### ISSUE TITLE
"(a=b).value" => "unresolved symbol"

### ISSUE THREAD

**Issue by boozook** [HaxeFoundation/intellij-haxe#29] opened 2014-10-11 22:10 UTC
![screen shot 2014-10-12 at 1 25 03](https://cloud.githubusercontent.com/assets/888526/4604312/52992a66-5192-11e4-91dc-3ddc367d9078.png)

I don't know how it's happening. Idea says "unresolved symbol" only :).

_next for copy-paste:_

``` haxe
using StringTools;
class Demo{
    function demo(){
        var lines = "--+--+--".split("+");
        for(i in 0...lines.length)
            if((lines[i] = lines[i].rtrim()).length > 0)
                trace(lines[i]);
    }
}
```

TIR: STB-7290

**Comment by sganapavarapu1** [comment] 2015-03-05 06:43
Even simpler cases like these are not working:

(new haxe.Timer(1000)).run();
(m[i]).length; // m is Array<String>

Any expression in paranthesis is not being interpreted correctly as HaxeReference.

**Comment by sganapavarapu1** [comment] 2015-03-05 06:46
I fixed most cases except the very two examples that fzzr mentioned.
That's because, in those two cases... it is unresolved on a local identifier. 
HaxeIdentifier is not of type HaxeReference (but it is inside HaxeReferenceExpression).
Also, some PSI compliance is missing for HaxeIdentifier.

So, I will commit the fixes made so far for handling other kinds of expressions in paranthesis.
I will update once I fix the HaxeIdentifier kinds as in examples by fzzr.

**Comment by sganapavarapu1** [comment] 2015-03-05 22:18
This kind of stuff is hard to resolve in current architecture.
I am unassigning this from me, I did partial work that resolved several expression types that are within paranthesis (which was not working earlier... but I did not resolve the 2 examples by fzzr and they are best resolved (1) either by implementing many unimplemented methods in HaxeReferenceImpl, HaxeIdentifierPsiMixInImpl (for PSI compliance) etc, (2) or by using Haxe compiler for type inference and code assist. Solution # 1 will not be robust enough and hard to keep up with language like Haxe because OpenAPI PSI is more Java oriented and does not encompass supporting all kinds that Haxe allows. Also the language changes needs frequent patches to implementation if # 1 route is taken. So, I'm suggested to go for # 2.

**Comment by mayakwd** [comment] 2017-05-24 16:26
Unresolved too:
```
var a:{v:Int} = {v:1};
var c = a.v; // <- unresolved
```

**Comment by EricBishton** [comment] 2017-05-24 22:23
Here's the current state at 0.11.0-RC3:
```haxe
class Demo{
    function demo(){
        var lines = "--+--+--".split("+");
        for(i in 0...lines.length)
            if((lines[i] = lines[i].rtrim()).length > 0) {  // <-- remains unresolved
                trace(lines[i]);
                lines[i].rtrim();
                StringTools.rtrim(lines[i]);  // <--rtrim is unresolved  -- Fixed!!
            }
    }
    function demo2() {
        var a = {v:1};
        var b = 1;

        var c = a.v; // <- unresolved

        var d = (a = (a.v + b)).v; // <- unresolved -- And should remain so!!
        var e = (a.v = (a.v + b)).v; // <- unresolved -- And should remain so!!
        var f = a;
        f.v = (a.v = (a.v + b));  // <- unresolved -- and should be -- both at f and internally.
    }

    function demo3() {
        var a:{v:Int} = {v:1};  // Specific typing doesn't seem to help.
        var c = a.v; // <- unresolved -- and should be
    }
}
```

**Comment by mayakwd** [comment] 2017-05-25 01:01
Hm, why it should remain to be unresolved? Isn't IDE's prime duty is to make coding easy and comfortable? :-)

**Comment by EricBishton** [comment] 2017-05-25 01:16
`var d = (a = (a.v + b)).v;` should remain unresolved -- marked as an error would be better -- because the type of sub-expression `(a = (a.v + b))` is an integer, not an anonymous type.  Integers don't have fields named .v.

For a more precise explanation, you can read my above comment from Oct 11, 2015.  The short story is: The last thing assigned `a =` is an integer, and this is still true if `a.v =` is assigned.  Parenthesis change evaluation ordering, but do not change the type of the value being assigned.  The whole anonymous type is a Red Herring.

**Comment by mayakwd** [comment] 2017-05-25 02:27
Well, ```(a.v+b).v ``` is obvious, but my question rather was about:
```
function demo3() {
        var a:{v:Int} = {v:1};  // Specific typing doesn't seem to help.
        var c = a.v; // <- unresolved -- and should be
    }
```

```a``` have field v, and it described in anonym type. Or it's just a copy-paste of the comment?

**Comment by EricBishton** [comment] 2017-05-25 02:31
Oh, you're right.  That one should resolve.  I fixed it in the comment above.

**Comment by EricBishton** [comment] 2020-09-09 07:22
Here's the state with 1.3.1.  Usings have been fixed (e.g. StringTools.rtrim() is found), and expressions inside of parenthesis now work.
```haxe
package ;
using StringTools;

class TestIssue29 {
    public function new() {
    }
}

class Demo{
    function demo(){
        var lines = "--+--+--".split("+");
        for(i in 0...lines.length)
            if((lines[i] = lines[i].rtrim()).length > 0) {  // <-- rtrim and length were unresolved -- Fixed!!
                trace(lines[i]);
                lines[i].rtrim();
                StringTools.rtrim(lines[i]);  // <--rtrim is unresolved  -- Fixed!!
            }
    }
    function demo2() {
        var a = {v:1};
        var b = 1;

        var c = a.v; // <- unresolved

        var d = (a = (a.v + b)).v; // <- unresolved -- And should remain so!!       // characters 17-30 : Int should be { v : Int }
        var e = (a.v = (a.v + b)).v; // <- unresolved -- And should remain so!!     // characters 16-35 : Int has no field v
        var f = a;
        f.v = (a.v = (a.v + b));  // <- unresolved -- and should be -- both at f and internally.
    }
    function demo3() {   // From mayakwd
        var a:{v:Int} = {v:1};
        var c = a.v; // <- unresolved
    }
    function demo4() {  // From Srikanth
        (new haxe.Timer(1000)).run();  // <- unresolved -- Fixed!!

        var m:Array<Int> = new Array<Int>(0);                                       // characters 42-43 : Too many arguments
        (m[i]).length; // m is Array  // <- unresolved -- Correct.                  // characters 11-12 : Unknown identifier : i
        (m).length;  // Works!!
    }
}
```

Still have to fix resolving fields in anonymous structs (which is what this bug was primarily about).

**Comment by m0rkeulv** [comment] 2024-08-05 14:36
looks like most things here works as intended, not sure why `f` is suppose to be unresolved, the type is inferred from var a, so so as far as i know it should resolve just fine (as it does).
![image](https://github.com/user-attachments/assets/cd9407d5-4e93-4834-bad1-c8339f945b20)

**Closed as completed by m0rkeulv** 2024-08-05 14:36 UTC
Labels: bug, Priority 2

**Comment by boozook** [comment] 2024-08-05 14:46
@m0rkeulv, that was ten years ago.

**Comment by m0rkeulv** [comment] 2024-08-05 15:32
i know, i am just closing issues that seems to be resolved.
The resolve of members from anonymous structures is a more recent change though, and now that its fixed i can close this issue as solved :)
