### ISSUE TITLE
Windows build error - Exact same command works in CMD but fails in Intellij Idea 2017.1.2

### ISSUE THREAD

**Issue by hedgehog90** [HaxeFoundation/intellij-haxe#659] opened 2017-08-08 17:34 UTC
This is the first message on attempting to compile:

Information:C:/Dev/Haxe/haxe-3.4.2/haxelib.exe run lime build C:/Users/hedge/Projects/Games/Test/project.xml windows -verbose

It eventually fails with:

Information:'cl.exe' is not recognized as an internal or external command,
I've also noticed it doesn't say 'Using MSVC version: 19' when it should.

However, if I run the exact same command in Command Prompt, it compiles without any issues.
I can only assume that the issue lies with  the plugin due to some kind of conflict.

I've tried invalidating the cache and restarting with no luck. Any ideas?

**Comment by EricBishton** [comment] 2017-08-08 18:22
Tell me if I'm wrong:  You start IDEA using the start menu or icon (not from the command line); and, when you start a command line, it runs a batch file to set up your development environment (like running MSVCVARS.bat).

If I am correct, then your issue is that the CMD shell and IDEA are actually using different run-time environments.  The easiest way to fix this (and verify that I am correct) is to start a CMD shell and do your "correct" build.  Then, _from that same shell_ start IDEA using "C:\Program Files\JetBrains\IntelliJ Idea 2017.1\bin\idea.bat".  Now run your build from inside IDEA.  If it works, you have verified my hypothesis.

How to fix it:  One way is to always start IDEA from your CMD shell.  The other is to add the environment variables from your CMD shell to your system-wide environment variables.  (Control Panel->System and Security->System->Advanced System Settings (left menu)->Environment Variables... (button))

**Comment by hedgehog90** [comment] 2017-08-08 21:50
OK, I tried what starting Intellij Idea from CMD with idea.bat. Build failed just the same as last time.

I'm not running MSVCVARS or any environment setup batch before running the build command in CMD.

The various VSCMNTOOLs are not in the path variable either, they are just variables.

When attempting to build with the plugin, I think hxcpp is failing to find any of the various VSxxxCOMNTOOLS I've got installed.

If I run the command in IDEA's Terminal panel, it works.

**Comment by m0rkeulv** [comment] 2017-09-17 21:38
I got the same issue on a pretty fresh windows 10 installation so the env. vars should not be messed up in any way (I thought maybe that was the reason why I couldn't get it to work in the first place). 

I think you could reproduce this by installing a fresh copy of windows on a virtual machine, then 

- install  haxe, openFL, Lime , 

- Setup  openFL and lime (installs C++ 2010 runtimes)

- Install Visual studio 2015 express/community edition

- Create a simple openFL project (openFL create "someProject"), 

- Create a new Haxe run configuration 

- Try run the application with openFL and Windows as target.

in my case both  the run and debug commands fails,  but I can copy the command from the output:

> Information:C:/HaxeToolkit/haxe/haxelib.exe run lime build C:/HaxeToolkit/projects/SimpleOpenGLView/project.xml windows –verbose

and run it both in intelliJs terminal and command prompt without problem, everything compiles fine and i can manually run the executable afterwards.

**Comment by EricBishton** [comment] 2017-09-17 22:15
Just wondering if this bug (https://github.com/HaxeFoundation/hxcpp/issues/590) is the cause of the problem.  What do you guys think?

**Comment by m0rkeulv** [comment] 2017-09-18 11:35
I used to get the

> 'cl.exe' is not recognized as an internal or external command

error before i reinstalled, this was due to messed up Env. vars i think, now on a clean install i can run the build command both in command prompt and intelliJ so i see no reason why the plugin should have any problem running it.

regarding the issue you linked, when i run  

> "%VS140COMNTOOLS%\vsvars32.bat"

i also get the 

> "ERROR: Cannot determine the location of the VS Common Tools folder"

but running the visual studio 2010 vsvars32.bat works just fine and seems to solve this.
"C:\Program Files (x86)\Microsoft Visual Studio 10.0\Common7\Tools"

My best guess is that the plugin get env-vars and/or paths messed up when you got multiple visual studio versions installed.

**Comment by EricBishton** [comment] 2017-09-18 18:16
The plugin doesn't do anything to manipulate (or filter) environment variables it doesn't already know about.  It only _reads_ HAXE_STD_PATH and HAXELIB_PATH.  It only _prepends_ (writes) to Path (or PATH, depending upon OS) to add the haxelib and/or neko directories.  Everything else is passed through unchanged.  It doesn't even know that MSVC or it's variables exist.

I'm not saying there is no bug here; I'm flummoxed as to what could be causing it.

Regarding the command prompt in IntelliJ (you may already understand this, but just to clarify):  Normal shell processing is performed when the shell is started.  That is to say, anything that runs automatically (via registry, .bashrc, etc.) to set up your environment will also be run automatically inside of the IntelliJ shell window -- because the shell is being forked.  However, IntelliJ IDEA, itself, will only see _that_ environment when it's started using idea.bat (or idea.sh) from a command shell.

**Comment by m0rkeulv** [comment] 2017-09-18 18:53
I see your point, but there is clearly something different between command line execution and plugin execution, the only thing I have found so far is that the processBuilder.environment() does not return the environment variables in the same order as “set” lists them  in the normal command line. I don’t know if this actually makes any difference, but I thought I should mention it anyway.

I might also have found a temp workaround, if I add

`<setenv name="VS140COMNTOOLS" value="disable" />`

to _**.hxcpp_config**_ the plugin seems to work again as it targets the 2010 version of cl.exe, the compile time takes forever though.

**Comment by m0rkeulv** [comment] 2017-09-18 20:26
Ok i have finally found the cause of the problem, at least with the code that is in the master branch.
`processBuilder.environment() ` will give you all your environment variables `GeneralCommandLine.getEnvironment()` on the other hand will not.

when the plugin executes getCommandForNeko() the HaxeCommandLine object (named commandLine) only got the  `path` variable, nothing else. 
so just as a hack i added this line to inject the environment variables
`commandLine.getEnvironment().putAll(new ProcessBuilder("").environment())`
and now the plugin works.

**Comment by EricBishton** [comment] 2017-09-18 21:00
Oh, really?  o_O  You may have just found the solution for another issue, too.  

.... And.... Thank YOU!! for figuring out how to build and debug the plugin.  Your help is GREATLY appreciated...

HaxeCommandLine (and its superclass, GeneralCommandLine) do not actually load the environment until right before execution.  Then it calculates an appropriate environment and overlays variables manually added.  That said, HaxeCommandLine.getEffectiveEnvironment() should give us what is actually given to the forked program, because it does the same thing.  Given that your hack has fixed the issue, it stands to reason that IDEA is manipulating the environment as it sees fit, rather than propagating it as I had understood.

The proper fix is going to be something like adding your hack to the constructor of HaxeCommandLine.  Do you want to do that and submit a PR?  Or do you just want me to go ahead and fix it?

**Comment by m0rkeulv** [comment] 2017-09-18 22:33
I tried to make a pull request but from the build status it looks like `getEffectiveEnvironment()` is not available in intelliJ14 & 15, i guess its only  in 2016 and later versions. if support for older version is a priority  we could probably go with `System.getenv()`

**Comment by EricBishton** [comment] 2017-09-18 23:00
I only suggested `getEffectiveEnvironment()` as a debugging tool -- to see what environment is really getting passed to the underlying process.  You can make the constructor of HaxeCommandLine use System.getenv().

In the future, if you find version incompatibilities, the classes in src/common/com/intellij/plugins/haxe/build are there to determine the version and to access fields, methods, and classes through reflection.

**Comment by m0rkeulv** [comment] 2017-09-18 23:32
I have updated my code and it now builds for all versions except 2017.2, it looks like the build script can’t download that version of intelliJ 

> Location: http://download-cf.jetbrains.com/idea/ideaIU-2017.2.tar.gz [following]
--2017-09-18 23:20:47--  http://download-cf.jetbrains.com/idea/ideaIU-2017.2.tar.gz
Resolving download-cf.jetbrains.com (download-cf.jetbrains.com)... 205.251.253.245, 205.251.253.21, 205.251.253.138, ...
Connecting to download-cf.jetbrains.com (download-cf.jetbrains.com)|205.251.253.245|:80... connected.
HTTP request sent, awaiting response... 403 Forbidden
2017-09-18 23:20:47 ERROR 403: Forbidden.
...
common.xml:75: IDEA installation not found.

**Comment by EricBishton** [comment] 2017-09-19 00:37
Yes, this happens regularly, since JetBrains removes older versions of  
IDEA from their web site.

I'll deal with it.  No worries.

-Eric


On Mon, 18 Sep 2017 16:32:32 -0700, m0rkeulv <notifications@github.com>  
wrote:

>
> I have updated my code and it now builds for all versions except 2017.2,  
> it looks like the build script can’t download >that version of intelliJ
>>
>> Location: http://download-cf.jetbrains.com/idea/ideaIU-2017.2.tar.gz  
>> [following]
>> --2017-09-18 23:20:47--  
>> http://download-cf.jetbrains.com/idea/ideaIU-2017.2.tar.gz
>> Resolving download-cf.jetbrains.com (download-cf.jetbrains.com)...  
>> 205.251.253.245, 205.251.253.21, >>205.251.253.138, ...
>> Connecting to download-cf.jetbrains.com  
>> (download-cf.jetbrains.com)|205.251.253.245|:80... >>connected.
>> HTTP request sent, awaiting response... 403 Forbidden
>> 2017-09-18 23:20:47 ERROR 403: Forbidden.
>> ...
>> common.xml:75: IDEA installation not found.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 
This email and any attachments may contain confidential and privileged  
material for the sole use of the intended recipient. Any review, copying,  
or distribution of this email (or any attachments) by others is  
prohibited. If you are not the intended recipient, please contact the  
sender immediately and permanently delete this email and any attachments.

**Comment by EricBishton** [comment] 2017-09-19 17:13
Fixed. PR #666

Thanks, @m0rkeulv

**Closed by EricBishton** 2017-09-19 17:13 UTC
Labels: bug, Needs Triage, Priority 4
