### ISSUE TITLE
Can't create "Haxe" libraries in the Project Structure window on Linux.

### ISSUE THREAD

**Issue by EricBishton** [HaxeFoundation/intellij-haxe#983] opened 2020-02-01 19:11 UTC
When manipulating the project structure, "Haxe" library is not an option when manipulating the module dependencies, making it impossible to add Haxe libraries to a module.

![image](https://user-images.githubusercontent.com/12093217/73597658-23f8e300-44e3-11ea-99fb-bd6871fa62de.png)

The menu item is also missing when creating libraries in the Project and Global levels.

Ubuntu 18.04.1 LTS.
IDEA 18.3, 19.X
Plugin: 1.2 and later.

Seems to work fine on Windows.

**Comment by gfaramaz** [comment] 2021-04-14 11:51
Confirm the bug for the 2021 version candidate (https://github.com/HaxeFoundation/intellij-haxe/pull/1085) on windows.

**Comment by Sartoric** [comment] 2021-08-19 15:47
Confirm the same on 
MacOs 10.13.6 (17G14042)
Plugin Latest pre-release 202104151903

IntelliJ IDEA 2021.1.3 UE - Build #IU-211.7628.21
IntelliJ IDEA 2021.2 UE - Build #IU-212.4746.92

**Comment by m0rkeulv** [comment] 2023-07-17 23:03
Unable to reproduce  on windows 10 and ubuntu 23.04 using intellij community 2023.1 and 1.4.7 version of plugin
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/602342b0-b618-4b54-8580-8274a7ff7c0e)
![image](https://github.com/HaxeFoundation/intellij-haxe/assets/3193925/8a4719e3-5e75-4b8b-9afd-9a1a79bfd42a)

**Comment by m0rkeulv** [comment] 2023-08-21 17:29
i am closing this issue as i am unable to reproduce the problem with  the latest releases.

**Closed by m0rkeulv** 2023-08-21 17:29 UTC
Labels: bug, Priority 1, might have been solved
