### ISSUE TITLE
Doesn't work in 2019.2.3

### ISSUE THREAD

**Issue by bronze7** [HaxeFoundation/intellij-haxe#970] opened 2019-10-21 05:47 UTC
I installed the plugin for version 2019.2.3 and it doesn't work. It doesn't recognize the imported libraries so ended up not recognizing most of the code. I created the project SDK and linked the path to Haxe folder but doesn't work out. If it's not supported for this version then it's my fault. I went ahead because it said that the plugin supports version 2019.x.

**Comment by EricBishton** [comment] 2019-10-21 06:01
Imported libraries usually need to be pointed at their "classpath" directory, specified in the libraries haxelib.json file.  For example, the library classpath for hx3compat is .../haxelib/hx3compat/1,0,3/std, and the classpath for hxcpp is .../haxelib/hxcpp/3,4,188/src.  Heaps, openfl, and lime use their libraries root directories (e.g. .../haxelib/lime/9,5,1).

For the SDK, the classpath and sourcpath should each have only one entry, at it should point to the "std" subdirectory of the SDK.

**Comment by BronzeViper** [comment] 2019-10-21 06:19
> 
> 
> Imported libraries usually need to be pointed at their "classpath" directory, specified in the libraries haxelib.json file. For example, the library classpath for hx3compat is .../haxelib/hx3compat/1,0,3/std, and the classpath for hxcpp is .../haxelib/hxcpp/3,4,188/src. Heaps, openfl, and lime use their libraries root directories (e.g. .../haxelib/lime/9,5,1).
> 
> For the SDK, the classpath and sourcpath should each have only one entry, at it should point to the "std" subdirectory of the SDK.
IntelliJ has automatically set the sourcepath and classpath to the correct location. In the File>ProjectStructure>SDK I have checked that the correct location is given.

As for the libraries part, I'm not quite understanding. Where can I find the haxelib.json file. 

Another thing I noticed is that the IDE is asking me to specify my project path in package ;
like Folder.SubFolder.source

**Comment by EricBishton** [comment] 2019-10-21 06:41
> Where can I find the haxelib.json file.

The haxelib.json file for each library is in the library's root directory: .../haxelib/hxcpp/3,4,188/haxelib.json.

If it has a "classpath" entry, then you must add that path to the library's root directory.  If there is no "classpath" entry, then the root directory itself will suffice.

>... the IDE is asking me to specify my project path in package ;

If your project is set up incorrectly, the expected package name will be incorrect.  In the "Project Structure...->Modules (left panel)-><module_name>(middle panel)->Sources(tab)", make sure that your source root(s) is(are) marked as "sources".  Generally speaking, your project root should not be considered a source directory; your `.../src` directory should.  The package detection mechanism will suggest (and expect) a path from one of these roots (the root name is not included). 

For example, if you have a file in the `.../myProject/src/foo/` directory named `bar.hx`, and you have set the project root to`.../myProject/src/`, the expected package entry in the `bar.hx` file would be `package foo;`

![image](https://user-images.githubusercontent.com/12093217/67182037-16d04200-f393-11e9-8ac1-4f7e7f91152f.png)

**Comment by BronzeViper** [comment] 2019-10-21 13:12
The classpath and sourcepath is set to "..\haxe\std". The module shows my source root as my src folder. Also the Haxe SDK is named Haxe NA (NA) (as in Not Available?). Setting the module helped removing the error on the package ; line but still classes, functions and variables are not identified by the IDE.

**Comment by EricBishton** [comment] 2019-10-21 20:14
Please either send your project files (.ipr and .iml) or a screenshot of the SDK configuration settings page, the module page, and the project page.  Also, please tell me the absolute paths of your project and the Haxe SDK on your computer.

If the SDK is "Haxe NA" it means that the plugin couldn't find (or didn't have permissions to run) the Haxe executable (Haxe.exe on Windows) in order to extract the version information.

**Comment by BronzeViper** [comment] 2019-10-22 07:46
Sure.
![classpath](https://user-images.githubusercontent.com/55687227/67266381-c27dad00-f4cd-11e9-9ac1-aedeba09dc93.png)
![sourcepath](https://user-images.githubusercontent.com/55687227/67266400-cf9a9c00-f4cd-11e9-8f88-9345cf1ff1a8.png)
![source](https://user-images.githubusercontent.com/55687227/67266425-db865e00-f4cd-11e9-8694-8455c2bae906.png)

Haxe toolkit is installed in D:\SDK\Haxe\Haxe 4\haxe\std\..
My project is in D:\Projects\Games\Haxe\MyGame\..

**Comment by CanIGetaPR** [comment] 2024-04-22 12:10
Suggesting this issue is closed as it was most likely caused by misconfigured class library paths and is related to a 5 year old IDE version.

**Closed** 2024-04-22 12:36 UTC
Labels: Awaiting Clarification
