### ISSUE TITLE
Not compatible with latest idea version. So nobody can use it any longer.

### ISSUE THREAD

**Issue by kledsen** [HaxeFoundation/intellij-haxe#991] opened 2020-04-11 15:03 UTC

**Comment by CanIGetaPR** [comment] 2020-04-15 17:37
Add support for IntelliJ IDEA 2020.1

**Comment by demurgos** [comment] 2020-04-17 16:13
The issue is already tracked at #975.

**Comment by eliasku** [comment] 2020-04-18 13:25
@kledsen @CanIGetaPR 
As quick workaround you could use my artifact plugin for 2020.1 - https://github.com/eliasku/intellij-haxe/releases/tag/1.2-2020

**Comment by kledsen** [comment] 2020-06-04 10:47
workaround doesn't work for me.
We'll stop using this plugin for good bc of this issue not resolving in any meaningful timeframe,
But thanks for the work here, we liked it while it lasted.

**Comment by EricBishton** [comment] 2020-08-02 05:35
2020.1 can be built with change https://github.com/HaxeFoundation/intellij-haxe/commit/48fca44f761a69d5d11683af58660bcc47066f13 on the develop branch.  Working on 2020.2...

**Comment by EricBishton** [comment] 2020-08-07 07:58
2020.2 builds can be built with change https://github.com/HaxeFoundation/intellij-haxe/commit/983af77c0887a7b95a9ab2e83bb6b9509b80c76f on the 'develop' branch.

**Comment by EricBishton** [comment] 2020-09-08 01:46
Fixed with https://github.com/HaxeFoundation/intellij-haxe/releases/tag/1.3

**Closed by EricBishton** 2020-09-08 01:46 UTC
Labels: Fixed, duplicate, enhancement
