### ISSUE TITLE
Interface Implementations not being found 2018

### ISSUE THREAD

**Issue by cmandlbaur** [HaxeFoundation/intellij-haxe#831] opened 2018-05-12 10:01 UTC
Go to implementations results in "No Implementations found" message.
The clickable gutter icon showing that an interface is implemented is missing. 

Was working in 2017, hasn't been in the 2018 versions I've used.

**Comment by mayakwd** [comment] 2018-05-17 13:03
Can't reproduce on EAP build.

**Comment by mayakwd** [comment] 2018-05-17 15:42
I've found the reason, going to fix it as soon as possible

**Comment by cmandlbaur** [comment] 2018-05-18 02:26
Thanks!

**Comment by mayakwd** [comment] 2018-09-13 21:37
The bad news is that it took too many time for me to face this issue again. 
The good news is that it's going to be fixed in new eap release.

**Comment by EricBishton** [comment] 2018-09-13 21:38
@mayakwd   What was the underlying problem?

**Comment by mayakwd** [comment] 2018-09-13 21:47
During indexing virtual file is not accessible through basic methods e.g. 
```haxe
file.getVirtualFile();
file.getOriginalElement().getContainingFile().getVirtualFile()
``` 
Instead of it FileBaseIndex storing it in PsiElement`s userdata as a key. 
This issue led to wrong search results during inheritance indexing.

**Closed** 2018-09-15 09:44 UTC
Labels: Priority 2, bug
